### ISSUE TITLE
Download/Incomplete directory, possibility to choose a local path on root disk

### ISSUE THREAD

**Issue by snow3461** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#13]
That's more of a feature request.

Could you make possible to choose a local path for download directory and incomplete directory?

Having to choose a shared folder, it make disks wake up all the time, whereas if the root disk is big enough, it can hold the downloads.

**Comment by snow3461** [comment]
This "problem" can easily be bypassed by shrinking the OS partition, making room for anoter one, and then create shared folders on this space.
Thanks @ryecoaaron for the suggestion. Never thought doing that.

**Comment by nohatssir** [comment]
This will not be added. When looking at how OMV is designed it doesn't really make sense since users can't really access the downloaded data easily that way. We could possibly add the choice to choose no shared folder and let the plugin use the default locations in the future though. But that still doesn't provide many gains, especially when there's ways around it anyway.
